spring:
    application:
        name: BigdataConsumer
    datasource:
        username: root
        url: jdbc:mysql://localhost:3306/bigdata-consumer?allowPublicKeyRetrieval=true&useSSL=false
        password: pass123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                show_sql: true
                format_sql: true
        show-sql: true

aws:
    region: us-east-1
    dynamodb:
        endpoint: http://localhost:4566
        units:
            capacity:
                write: 5
                read: 5
    access:
        key:
            id: 1
    secret:
        access:
            key: 123
